export const InvoiceData = [
  {
    id: 1,
    customerEmail: "Productbob21@gmail.com",
    invoiceNo: "AZA1234BOX",
    amount: "₦50,000",
    created: "5th, October 2021",
    status: "Due",
  },
  {
    id: 2,
    customerEmail: "Productbob21@gmail.com",
    invoiceNo: "AZA1234BOX",
    amount: "₦50,000",
    created: "5th, October 2021",
    status: "Due",
  },
  {
    id: 3,
    customerEmail: "Productbob21@gmail.com",
    invoiceNo: "AZA1234BOX",
    amount: "₦50,000",
    created: "5th, October 2021",
    status: "Due",
  },
  {
    id: 4,
    customerEmail: "Productbob21@gmail.com",
    invoiceNo: "AZA1234BOX",
    amount: "₦50,000",
    created: "5th, October 2021",
    status: "Due",
  },
  {
    id: 5,
    customerEmail: "Productbob21@gmail.com",
    invoiceNo: "AZA1234BOX",
    amount: "₦50,000",
    created: "5th, October 2021",
    status: "Due",
  },
  {
    id: 6,
    customerEmail: "Productbob21@gmail.com",
    invoiceNo: "AZA1234BOX",
    amount: "₦50,000",
    created: "5th, October 2021",
    status: "Due",
  },
  {
    id: 7,
    customerEmail: "Productbob21@gmail.com",
    invoiceNo: "AZA1234BOX",
    amount: "₦50,000",
    created: "5th, October 2021",
    status: "Due",
  },
  {
    id: 8,
    customerEmail: "Productbob21@gmail.com",
    invoiceNo: "AZA1234BOX",
    amount: "₦50,000",
    created: "5th, October 2021",
    status: "Due",
  },
];
